Makefile.inc: Add support for building AMD Onyx coreboot.
linuxboot/osf-builder pull request #8
Opened 2023-01-09 17:19 UTC by ed-sharma

This change uses an AMD coreboot defined variable from their projects Makefile, to avoid using the Intel specific coreboot config changes implemented in the osf-builder Makefile.inc

Signed-off-by: Eddie Vas <aeddiesharma@meta.com>

2023-01-10 00:57 UTC, jonzhang-fb requested changes

2023-01-11 02:00 UTC, ed-sharma commented on Makefile.inc
> +	ifndef ONYX_BUILD
The previous change had a mistake. I need to define control more content than the one just under the control of COREBOOT_BLOBS_DIR define, so the define approach may not be the right one. Changed the names and other suggestions.

2023-01-11 03:32 UTC, jonzhang-fb approved these changes

2023-01-11 03:33 UTC, jonzhang-fb approved these changes

2023-01-11 06:48 UTC, dhendrix commented
The changes look good, but I think the commit message needs to be updated. It appears that we're really just telling the Makefile not to worry about Intel blobs. That doesn't necessarily have anything to do with AMD.

(fwiw, I'm also looking at builds for other chips: #5

2023-01-11 10:37 UTC, ArthurHeymans commented on Makefile.inc
> +		sed -i "s|CONFIG_PAYLOAD_FILE=.*|CONFIG_PAYLOAD_FILE=\"$(KERNEL_IN)\"|" $@
Payload is not an Intel blobs thing?

2023-01-11 19:40 UTC, ed-sharma commented on Makefile.inc
> +		sed -i "s|CONFIG_PAYLOAD_FILE=.*|CONFIG_PAYLOAD_FILE=\"$(KERNEL_IN)\"|" $@
Good catch

2023-01-11 19:56 UTC, jonzhang-fb approved these changes
LGTM. @dhendrix @ArthurHeymans I will merge this PR if no additional comment till Friday.

2023-01-11 20:03 UTC, ArthurHeymans approved these changes

2023-01-11 20:04 UTC, ArthurHeymans commented
> LGTM. @dhendrix @ArthurHeymans I will merge this PR if no additional comment till Friday.

Looks good now. LGTM

2023-01-12 02:23 UTC, merged